#!/bin/bash

if [ ! -d target ] || [ ! -f classpath.txt ]
then
	mvn clean package
	mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt
fi

RWS_CP=target/classes:`cat classpath.txt`
RWS_HOSTNAME=`hostname -f`

PARAMS=`cat params`

PIDFILE=chord.pid
OUTFILE=chord.out
ERRFILE=chord.err

nohup java -Djava.net.preferIPv4Stack=true -cp $RWS_CP de.rwglab.p2pts.TripleStoreMain $PARAMS 1> $OUTFILE 2> $ERRFILE &
echo $! >> $PIDFILE
