/*
 * This file is part of Chordless. Chordless is free software: you can redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version. Chordless is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details. You should have received a copy of the GNU General Public License along with
 * Chordless. If not, see <http://www.gnu.org/licenses/>. Copyright 2009 Martin Kihlgren <zond at troja dot ath dot cx>
 */
/*
 * Monitor.java Created on March 5, 2009, 2:30 PM
 */

package cx.ath.troja.chordless.gui;


/**
 * 
 * @author zond
 */
public class Monitor extends javax.swing.JFrame {

	private boolean listening = false;

	/** Creates new form Monitor */
	public Monitor() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		monitorPanel1 = new cx.ath.troja.chordless.gui.MonitorPanel();
		switchButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		monitorPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

		switchButton.setText("Send start");
		switchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				switchMonitoring(evt);
			}
		});

		javax.swing.GroupLayout monitorPanel1Layout = new javax.swing.GroupLayout(monitorPanel1);
		monitorPanel1.setLayout(monitorPanel1Layout);
		monitorPanel1Layout.setHorizontalGroup(monitorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				monitorPanel1Layout.createSequentialGroup().addContainerGap(294, Short.MAX_VALUE).addComponent(switchButton).addContainerGap()));
		monitorPanel1Layout.setVerticalGroup(monitorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				monitorPanel1Layout.createSequentialGroup().addContainerGap().addComponent(switchButton).addContainerGap(265, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(monitorPanel1,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(monitorPanel1,
				javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void send(boolean what) {
		listening = what;
		if (what) {
			switchButton.setText("Send stop");
		} else {
			switchButton.setText("Send start");
		}
		monitorPanel1.send(what);
	}

	private void switchMonitoring(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_switchMonitoring
		if (listening) {
			send(false);
		} else {
			send(true);
		}
	}// GEN-LAST:event_switchMonitoring

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Monitor().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private cx.ath.troja.chordless.gui.MonitorPanel monitorPanel1;

	private javax.swing.JButton switchButton;
	// End of variables declaration//GEN-END:variables

}
